name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    check:
        runs-on: ubuntu-22.04

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v3
                with:
                    fetch-depth: 1

            -   name: Cache venv
                id: venv_ubuntu22
                uses: actions/cache@v3
                with:
                    path: .venv
                    key: venv_ubuntu22_${{ hashFiles('pdm.lock') }}

            -   name: Set up venv
                if: steps.venv_ubuntu22.outputs.cache-hit != 'true'
                run: |
                    python3.10 -m venv ".venv"
                    source .venv/bin/activate
                    pip install pdm==2.10.2
                    pdm install

            -   name: Format
                run: |
                    source .venv/bin/activate
                    pdm run format

            -   name: Lint
                run: |
                    source .venv/bin/activate
                    pdm run lint

            -   name: Type
                run: |
                    source .venv/bin/activate
                    pdm run type
